### ISSUE TITLE
Is backing buffer dynamically resizable?

### ISSUE THREAD

**Issue by skyne98** [diwic/shmem-ipc#1]
Hey there! First of all, great work!

Right now I am playing around with `shmem_ipc` as a potential backend for my tiny RPC library. However, I am encountering a problem where after writing > CAPACITY via `send_raw` data on the other side becomes garbled and incomplete, failing my validation. It seems to me like buffer just gets completely saturated and stops the flow of data.

Is there a way around it? Maybe I can somehow reset the pointer of this buffer to zero before I send each new message or something like that?

Thanks!

**Comment by diwic** [comment]
Hi,
To answer your question in the title, the backing buffer is not dynamically resizable. This is indeed a limitation but it makes the implementation a lot simpler (and probably faster) on both sides.

I'm not sure exactly what your actual problem is; and if you think it's a bug in the library or if you're just unsure of how to use it. Maybe you can clarify.

But if you're sending fixed size packets; then I recommend making that packet your `T` (in `Sender<T>`), that will ensure the ring buffer will never wrap around having some bytes of `T` at the end of the buffer and other bytes in the beginning.

If your packets are of variable size but still need to keep a packet intact in memory, then I'd suggest something like, if the Sender figures that it can't fit the packet, don't write half the packet but write some marker indicating to the receiver side that it should consider that marker an "no op". Fill the end of the buffer with "no op", then call `send_raw` again to continue writing to the beginning of the buffer.

**Comment by skyne98** [comment]
To clarify, I am pretty sure it's just my current lack of understanding of the inner workings of the system which are holding me back. My packets are of variable size, as I am aiming to transfer arbitrary arrays of binary data or arbitrary strings. If I understand correctly, you are suggesting checking the state's `remaining` value to see if the current packet will fit and in case it doesn't, send a no-op packet of the `remaining` size to “reset” the buffer. I guess that in this case, it would also make sense to make sure a packet is never bigger than the whole buffer and preventively throw errors.

I will definitely try this out right away!

**Comment by diwic** [comment]
Okay, so you want to send a packet of `packet_size` bytes and you don't want the packet to end up splitted.
It was not a use case I anticipated when I designed shmem-ipc, but I think you could do something like

 1) check `sender_mut.write_count()`. If `packet_size` is larger than that, the ringbuffer is full and you have to wait for the receiver and try again later.

 2) Call `send_raw` and check the `count` parameter coming into the closure. If `count >= packet_size`, just write the packet and we're done.

 3) Otherwise, write a no-op packet of `count` bytes and return from the closure.

 4) Call send_raw again, and see if `count >= packet_size`. If so, write the packet. If not, you'll have to wait for the receiver and try again later.

**Comment by skyne98** [comment]
Did exactly that yesterday and worked perfectly (specifically steps 2-4), thanks for the tip in your previous post!

**Comment by diwic** [comment]
@skyne98 Looking back at my instructions, as a minor optimisation you can check `Status.remaining` after step 3 (returned from `send_raw`) to see if there is any use in calling send_raw again or if you have to wait.
